ARG BUILD_ENV=default

FROM explori-backend-base-image AS common_pre_build
ONBUILD WORKDIR /explori/celery

FROM common_pre_build AS prod_build
ONBUILD COPY src/ src/
ONBUILD COPY data/uploaded/demo_ocel.jsonocel data/uploaded/demo_ocel.jsonocel

FROM common_pre_build AS dev_build

FROM ${BUILD_ENV}_build
# CMD ["env", "PYTHONUNBUFFERED=1", "EXPLORI_REDIS_HOST=${REDIS_HOST}", "EXPLORI_REDIS_PORT=${REDIS_PORT}", "PYTHONPATH=src/", "celery", "--app=worker.main.app", "worker", "--loglevel=INFO"]
CMD ["sh", "-c", "PYTHONUNBUFFERED=1 EXPLORI_REDIS_HOST=${REDIS_HOST} EXPLORI_REDIS_PORT=${REDIS_PORT} PYTHONPATH=src/ celery --app=worker.main.app worker --loglevel=INFO"]
