ARG BUILD_ENV=default

FROM explori-backend-base-image AS common_pre_build
ONBUILD WORKDIR /explori/fastapi

FROM common_pre_build AS prod_build
ONBUILD COPY src/ src/
ONBUILD COPY data/uploaded/demo_ocel.jsonocel data/uploaded/demo_ocel.jsonocel

FROM common_pre_build AS dev_build
ONBUILD ENV DEV=1

FROM ${BUILD_ENV}_build
# CMD ["env", "DEV=${DEV}", "PYTHONUNBUFFERED=1", "EXPLORI_REDIS_HOST=${REDIS_HOST}", "EXPLORI_REDIS_PORT=${REDIS_PORT}", "PYTHONPATH=src/", "uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8080"]
CMD ["sh", "-c", "DEV=${DEV} PYTHONUNBUFFERED=1 EXPLORI_REDIS_HOST=${REDIS_HOST} EXPLORI_REDIS_PORT=${REDIS_PORT} PYTHONPATH=src/ uvicorn server.main:app --host 0.0.0.0 --port 8080"]
